Zone Changelog: filter and paginate
operasoftware/dns-ui pull request #190
Opened 2022-03-08 11:55 UTC by uedvt359

Most of what I'd consider controversial takes place in `models/zone.php:list_changesets()`:
- It now takes an optional parameter for a list of filters (search comment, date range, pagination)
- It now returns two values (changes as before, plus total number of pages) => this is a breaking (internal) change, so all usages were updated.
- Items per page is for now hardcoded in there to 200. I'm open to improve this (config.ini knob?) if this is a problem.
- The SQL statement to select changelog entries is now relatively complex. To allow for the optional filter parameters, they have to be passed twice. This is a bit ugly, but I don't see a nicer alternative (assembling the SQL query as a string with if/else seems even worse).

I'm also a bit unhappy with the amount of `<?php...?>` blocks for pagination in `templates/zone.php` but there's just a lot of cases to check.

### commit message:

Implements:
- filter by comment (default all)
- filter by date range (default all)
- paginate results (200 items per page)

Filtering by author, while possible, is not implemented in this patch,
since we don't care about it. Note that the changelog displayed on a
user's profile is not touched; it continues to be unpaginated and
unfilterable for the same reason.

fixes #179

2022-04-19 07:12 UTC, uedvt359 commented
I hope this doesn't come across as pushy, but do you have the time to review this please, @thomas-pike?

2022-04-23 16:29 UTC, thomas-pike commented
> I hope this doesn't come across as pushy

Not at all, thanks for reminding me to look at this. I'll take a look now.

2022-04-23 21:01 UTC, thomas-pike requested changes

2022-04-26 06:41 UTC, uedvt359 commented on model/zone.php
> +		$stmt->bindParam(2, is_null($comment), PDO::PARAM_BOOL);
oof, embarrasing mistake! thanks for the review!

2022-04-26 08:51 UTC, thomas-pike approved these changes

2022-04-26 08:57 UTC, merged

2022-04-26 08:58 UTC, thomas-pike commented
Thank you for your continued contributions!